# Install nginx
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

# Copy Nginx configuration for AGAMA
- name: Copy Nginx config to sites-enabled
  ansible.builtin.copy:
    src: roles/nginx/files/default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

# Ensure nginx service is running and enabled
- name: Ensure Nginx service is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true