- name: Install haproxy
  apt:
    name: haproxy
    state: present

- name: Copy the Haproxy config
  template:
    src: haproxy.cnf.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0600
  notify: Restart Haproxy

- name: Ensure HAProxy is enabled and started
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: started

- name: Install prometheus-haproxy-exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter
    state: present
    update_cache: yes

- name: Update prometheus-haproxy-exporter ARGS
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-haproxy-exporter
    regexp: '^ARGS='
    line: 'ARGS="--haproxy.scrape-uri=http://127.0.0.1:9188/metrics;csv"'
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus-haproxy-exporter

- name: Ensure prometheus-haproxy-exporter is running
  ansible.builtin.systemd:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true

- name: Ensure prometheus-haproxy-exporter is enabled and started
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    enabled: true
    state: started

- name: Add CNAME for HAProxy instances
  community.general.nsupdate:
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key_secret }}"
    zone: "{{ domain_name }}"
    record: "{{ item.name }}.{{ domain_name }}."
    type: CNAME
    value: "{{ item.target }}.{{ domain_name }}."
  loop:
    - { name: "lb-1", target: "andriikuiava-1" }
    - { name: "lb-2", target: "andriikuiava-2" }
  notify: restart prometheus-haproxy-exporter
  no_log: true
