- name: Install haproxy
  apt:
    name: haproxy
    state: present

- name: Copy the Haproxy config
  template:
    src: haproxy.cnf.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0600
  notify: Restart Haproxy

- name: Install prometheus-haproxy-exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter
    state: present
    update_cache: yes

- name: Update prometheus-haproxy-exporter ARGS
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-haproxy-exporter
    regexp: '^ARGS='
    line: 'ARGS="--haproxy.scrape-uri=http://127.0.0.1:9188/metrics;csv"'
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus-haproxy-exporter

- name: Ensure prometheus-haproxy-exporter is running
  ansible.builtin.systemd:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true
