- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes

- name: Ensure Grafana is started and enabled
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Configure Grafana.ini file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana

- name: Provision Prometheus datasource
  ansible.builtin.copy:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
    owner: grafana
    group: grafana
    mode: "0644"

- name: Configure Grafana dashboards.yaml
  ansible.builtin.copy:
    src: dashboards.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
    owner: grafana
    group: grafana
    mode: "0644"
  notify: Restart Grafana

- name: Provision Main Dashboard
  ansible.builtin.copy:
    src: main.json
    dest: /etc/grafana/provisioning/dashboards/main.json
    owner: grafana
    group: grafana
    mode: "0644"