---
- name: Initial setup
  hosts: all
  roles:
    - init

- name: DNS Servers
  hosts: dns_servers
  roles:
    - bind

- name: Prometheus Servers
  hosts: prometheus_servers
  roles:
    - prometheus
    - grafana

- name: Database Server
  hosts: db_servers
  roles:
    - mysql

- name: Web Servers
  hosts: web_servers
  roles:
    - nginx
    - agama
    - uwsgi

