---
- name: Initial setup
  hosts: all
  roles:
    - init

- name: Keepalived
  hosts: keepalived_servers
  roles:
      - haproxy
      - keepalived
  tags:
      - switchover

- name: DNS Servers
  hosts: dns_servers
  roles:
    - bind

- name: Web Servers
  hosts: web_servers
  roles:
    - docker
    - agama
    - nginx
  tags:
    - switchover

- name: Database Server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - switchover

- name: Prometheus Servers
  hosts: prometheus_servers
  roles:
    - prometheus
    - influxdb
    - agama-client
    - docker
    - grafana
  tags:
    - prometheus

