---
- name: Always gather facts for all hosts
  hosts: all
  gather_facts: yes
  tags:
    - always
  tasks: []

- name: Initial setup
  hosts: all
  roles:
    - init
  tags:
    - init

- name: DNS Servers
  hosts: dns_servers:children
  roles:
    - bind
  tags:
    - bind

- name: Resolv DNS
  hosts: all
  roles:
    - resolv_dns
  tags:
    - resolv_dns

- name: Database Server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - mysql

- name: Prometheus Servers
  hosts: prometheus_servers
  roles:
    - prometheus
  tags:
    - prometheus

- name: Docker
  hosts: docker_servers
  roles:
    - docker
  tags:
    - docker

- name: Grafana Tasks
  hosts: grafana_servers
  roles:
    - grafana
  tags: grafana

- name: Agama tasks
  hosts: agama_servers
  roles:
    - agama
  tags: agama

- name: Agama client tasks
  hosts: agama_clients
  roles:
    - agama_client
  tags: agama_client

- name: Web server tasks
  hosts: web_servers
  roles:
    - nginx
  tags: web

- name: Influxdb tasks
  hosts: influxdb_servers
  roles:
    - influxdb
  tags: influxdb

- name: Haproxy tasks
  hosts: haproxy_servers
  roles:
    - haproxy
  tags: haproxy

- name: Keepalived tasks
  hosts: keepalived_servers
  roles:
    - keepalived
  tags: keepalived