---
- name: Initial setup
  hosts: all
  roles:
    - init

- name: Database server
  hosts: db_servers
  roles:
    - mysql
    - bind
    - prometheus

- name: Web server
  hosts: web_servers
  roles:
    - dns
    - agama
    - nginx
    - uwsgi