{
 "title": "Backups",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Incremental Backups influxdb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(backups_total{service=\"influxdb\", type=\"incremental\"}) by (service, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incremental Backups mysql",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(backups_total{service=\"mysql\", type=\"incremental\"}) by (service, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Backup Success Time mysql",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{service=\"mysql\", user = \"andriikuiava\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Backup Success Time influxdb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{service=\"influxdb\", user = \"andriikuiava\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB full backups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(backups_total{service=\"influxdb\", type=\"full\"}) by (service, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full mysql backups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(backups_total{service=\"mysql\", type=\"full\"}) by (service, type)",
     "legendFormat": "{{service}} {{type}}"
    }
   ]
  }
 ]
}