---
- name: Create /opt/agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Agama files
  ansible.builtin.get_url:
    dest: "/opt/agama/{{ item.dest }}"
    url: "{{ item.url }}"
    mode: "0644"
  loop:
    - {
      dest: "agama.py",
      url: "https://raw.githubusercontent.com/hudolejev/agama/master/agama.py",
    }
    - {
      dest: "Dockerfile",
      url: "https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile",
    }

- name: Build Agama Docker image
  community.docker.docker_image:
    name: agama
    build:
      path: /opt/agama
      network: host
    source: build

- name: Run Agama Docker container
  community.docker.docker_container:
    name: agama
    image: agama
    state: started
    restart_policy: always
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    ports:
      - "{{ agama_port }}:8000"
  no_log: true