---
# Install MySQL server
- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: yes

# Install PyMySQL for MySQL connectivity
- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

# Ensure MySQL service is started and enabled
- name: Ensure MySQL service is running
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

# Create override configuration for MySQL to bind to 0.0.0.0
- name: Create MySQL override configuration
  ansible.builtin.copy:
    dest: /etc/mysql/mysql.conf.d/override.cnf
    content: |
      [mysqld]
      bind-address = 0.0.0.0
  notify: Restart MySQL

# Create MySQL database
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Create MySQL user for the web application
- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Install MySQL exporter
- name: Install MySQL exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: present
    update_cache: yes

# Create MySQL user for the exporter
- name: Create MySQL user for exporter
  community.mysql.mysql_user:
    name: mysql_exporter
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT"
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Configure MySQL exporter credentials
- name: Configure MySQL exporter credentials
  ansible.builtin.copy:
    dest: /var/lib/prometheus/.my.cnf
    content: |
      [client]
      user=mysql_exporter
      password={{ mysql_exporter_password }}
    owner: prometheus
    group: prometheus
    mode: "0600"

# Create override configuration for MySQL exporter
- name: Restart MySQL exporter if credentials change
  ansible.builtin.systemd:
    name: prometheus-mysqld-exporter
    state: restarted
  notify: Restart MySQL Exporter