---
- name: Restart InfluxDB
  ansible.builtin.systemd:
    name: influxdb
    state: restarted

- name: Restart Telegraf
  ansible.builtin.systemd:
    name: telegraf
    state: restarted

- name: Restart InfluxDB Stats Exporter
  ansible.builtin.systemd:
      name: prometheus-influxdb-stats-exporter
      state: restarted

- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: yes