- name: Install keepalived
  apt:
    name: keepalived
    state: present

- name: Copy check script to keepalived_script user's home folder
  copy:
    src: script.sh
    dest: /root/check_script.sh
    owner: root
    group: root
    mode: '0755'

- name: Copy the Keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  become: true
  notify: Restart keepalived

- name: Download Keepalived Exporter
  get_url:
    url: https://github.com/mehdy/keepalived-exporter/releases/download/v1.4.0/keepalived-exporter_1.4.0_linux_amd64.tar.gz
    dest: /usr/local/bin/keepalived-exporter-1.4.0.linux-amd64.tar.gz

- name: Extract Keepalived Exporter
  ansible.builtin.unarchive:
    src: /usr/local/bin/keepalived-exporter-1.4.0.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Create systemd unit file
  template:
    src: keepalived_systemd.conf
    dest: /etc/systemd/system/keepalived-exporter.service
    owner: root
    group: root
    mode: '0644'
  no_log: true
  notify: Reload systemd

- name: Start the service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - keepalived
    - keepalived-exporter
