- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Configure Prometheus Service
  ansible.builtin.template:
    src: "templates/prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"
  notify:
    - Stop Prometheus
    - Daemon Reload
    - Start Prometheus

- name: Configure Prometheus
  ansible.builtin.template:
    src: "templates/prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
  notify:
    - Stop Prometheus
    - Daemon Reload
    - Start Prometheus

- name: Run Prometheus
  ansible.builtin.service:
    name: prometheus.service
    state: started

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Configure Nginx
  ansible.builtin.copy:
    src: templates/nginx_default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started