---
# Install Prometheus
- name: Download Prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes
    creates: /opt/prometheus-2.37.0.linux-amd64

- name: Symlink Prometheus binary
  ansible.builtin.file:
    src: /opt/prometheus-2.37.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    state: link

- name: Copy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/prometheus-2.37.0.linux-amd64/prometheus.yml
    owner: prometheus
    mode: '0644'
  notify: Restart Prometheus

- name: Create Prometheus service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Monitoring
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus --config.file=/opt/prometheus-2.37.0.linux-amd64/prometheus.yml
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Ensure Prometheus service is running and enabled
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true