- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Stop Prometheus
  service:
    name: prometheus.service
    state: stopped

- name: Start Prometheus
  service:
    name: prometheus.service
    state: started

- name: Daemon Reload
  ansible.builtin.systemd_service:
    daemon_reload: true