---
# Install Bind9
- name: Install Bind9
  ansible.builtin.apt:
    name:
      - bind9
      - python3-dnspython
    state: present
    update_cache: true

# Configure DNS forwarders in Bind9
- name: Configure DNS forwarders
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart Bind9
  no_log: true

# Create DNS zone file for megacoolproject.io
- name: Create master zone file
  ansible.builtin.template:
    src: db.megacoolproject.j2
    dest: /var/cache/bind/db.megacoolproject.io
    owner: bind
    group: bind
    mode: "0644"
    force: no
#  when: inventory_hostname in groups['dns_primary']
  notify:
    - Restart Bind9
    - Reload Bind9

- name: Create reverse zone file
  ansible.builtin.template:
    src: db.reverse.j2
    dest: /var/cache/bind/db.reverse
    owner: root
    group: root
    mode: "0644"
    force: no
#  when: inventory_hostname in groups['dns_primary']
  notify:
    - Restart Bind9
    - Reload Bind9

# Configure master zone in Bind9
- name: Configure Bind9 zones
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: "0644"
  notify: Reload Bind9

- name: Run handlers
  meta: flush_handlers

# Ensure Bind9 service is started and enabled
- name: Ensure Bind9 is running and enabled on boot
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true

# Download and install Bind9 exporter
- name: Download Bind9 exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus-community/bind_exporter/releases/download/v0.6.1/bind_exporter-0.6.1.linux-amd64.tar.gz
    dest: /opt/bind_exporter.tar.gz

# Unarchive Bind9 exporter
- name: Unarchive Bind9 exporter
  ansible.builtin.unarchive:
    src: /opt/bind_exporter.tar.gz
    dest: /opt/
    remote_src: yes

# Create symlink for Bind9 exporter
- name: Create symlink for Bind9 exporter
  ansible.builtin.file:
    src: /opt/bind_exporter-0.6.1.linux-amd64/bind_exporter
    dest: /usr/local/bin/prometheus-bind-exporter
    state: link

# Create systemd service for Bind9 exporter
- name: Create systemd service for Bind9 exporter
  ansible.builtin.template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
  notify: Reload Systemd

# Start Bind9 exporter service
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

# Start Bind9 exporter service
- name: Start Bind9 exporter service
  ansible.builtin.systemd:
    name: bind_exporter
    state: started
    enabled: true
  notify: Restart Bind9

- name: Add A record for backup server
  community.general.nsupdate:
    key_name: "nsupdate.key"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key_secret }}"
    zone: "megacoolproject.io"
    record: "backup.{{ domain_name }}."
    type: A
    value: "{{ backup_server_ip }}"
  no_log: true


- name: Add CNAME for Bind9 servers
  community.general.nsupdate:
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key_secret }}"
    zone: "{{ domain_name }}"
    record: "{{ item.name }}.{{ domain_name }}."
    type: CNAME
    value: "{{ item.target }}.{{  domain_name  }}."
  loop:
    - { name: "ns-1", target: "andriikuiava-1" }
    - { name: "ns-2", target: "andriikuiava-2" }
    - { name: "ns-3", target: "andriikuiava-3" }
  no_log: true