---
# Install Bind9
- name: Install Bind9
  ansible.builtin.apt:
    name: bind9
    state: present
    update_cache: true

# Ensure Bind9 service is started and enabled
- name: Ensure Bind9 is running and enabled on boot
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true

# Configure DNS forwarders in Bind9
- name: Configure DNS forwarders
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart Bind9

# Create DNS zone file for megacoolproject.io
- name: Create master zone file
  ansible.builtin.template:
    src: db.megacoolproject.j2
    dest: /var/cache/bind/db.megacoolproject.io
    owner: bind
    group: bind
    mode: '0644'
  notify: Restart Bind9


# Configure master zone in Bind9
- name: Ensure master zone for megacoolproject.io is configured
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.local
    block: |
      zone "megacoolproject.io" {
          type master;
          file "/var/cache/bind/db.megacoolproject.io";
      };
    marker: "# {mark} ANSIBLE MANAGED BLOCK for megacoolproject.io"
  notify: Reload Bind9

# Install Prometheus Node Exporter
- name: Install Prometheus Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
    update_cache: yes

# Ensure Prometheus Node Exporter is running and enabled
- name: Ensure Prometheus Node Exporter service is running
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true